export const nigerianMedicationAliases = [
  { rxcui: "161", genericName: "Paracetamol", category: "Analgesic", aliases: ["Panadol", "Emzor Paracetamol", "Boska", "M&B Paracetamol", "Avro Paracetamol"], source: "NAFDAC Greenbook / Nigerian pharmacy listings" },
  { rxcui: "LOCAL-PARACETAMOL-CAFFEINE", genericName: "Paracetamol + Caffeine", category: "Analgesic combination", aliases: ["Panadol Extra", "Boska", "Emzor Paracetamol Extra"], source: "NAFDAC Greenbook / Nigerian pharmacy listings" },
  { rxcui: "LOCAL-PARACETAMOL-CHLORPHENIRAMINE-PSEUDOEPHEDRINE", genericName: "Paracetamol + Chlorpheniramine + Pseudoephedrine", category: "Cold remedy", aliases: ["Procold", "Sudrex", "Coldcap", "Actifed Cold"], source: "Nigerian OTC brand mapping" },
  { rxcui: "733", genericName: "Ampicillin", category: "Antibiotic", aliases: ["Ampiclox"], source: "Nigerian pharmacy brand mapping" },
  { rxcui: "2625", genericName: "Cloxacillin", category: "Antibiotic", aliases: ["Ampiclox", "Cloxapen"], source: "Nigerian pharmacy brand mapping" },
  { rxcui: "18343", genericName: "Artemether", category: "Antimalarial", aliases: ["Coartem", "Lonart", "Amatem", "Lumartem", "Artefan", "Lokmal", "Arenax Plus"], source: "Nigerian pharmacy listings" },
  { rxcui: "847728", genericName: "Lumefantrine", category: "Antimalarial", aliases: ["Coartem", "Lonart", "Amatem", "Lumartem", "Artefan", "Lokmal", "Arenax Plus"], source: "Nigerian pharmacy listings" },
  { rxcui: "LOCAL-ARTEMETHER-LUMEFANTRINE", genericName: "Artemether + Lumefantrine", category: "Antimalarial combination", aliases: ["Coartem", "Lonart", "Amatem", "Lumartem", "Artefan", "Lokmal", "Arenax Plus"], source: "Nigerian pharmacy listings" },
  { rxcui: "18346", genericName: "Artesunate", category: "Antimalarial", aliases: ["Camosunate", "Arinate", "Larinate", "Combisunate"], source: "Nigerian antimalarial listings" },
  { rxcui: "LOCAL-ARTESUNATE-AMODIAQUINE", genericName: "Artesunate + Amodiaquine", category: "Antimalarial combination", aliases: ["Camosunate", "Larimal", "Artesam", "Coarsucam"], source: "Nigerian antimalarial listings" },
  { rxcui: "LOCAL-DIHYDROARTEMISININ-PIPERAQUINE", genericName: "Dihydroartemisinin + Piperaquine", category: "Antimalarial combination", aliases: ["P-Alaxin", "D-Artepp", "Duo-Cotecxin", "Artekin", "Dartepp"], source: "Nigerian antimalarial listings" },
  { rxcui: "LOCAL-ARTEROLANE", genericName: "Arterolane", category: "Antimalarial", aliases: ["Synriam"], source: "Nigerian antimalarial brand mapping" },
  { rxcui: "LOCAL-PIPERAQUINE", genericName: "Piperaquine", category: "Antimalarial", aliases: ["Synriam", "Piperaquine Phosphate"], source: "Nigerian antimalarial brand mapping" },
  { rxcui: "6922", genericName: "Metronidazole", category: "Antibiotic / antiprotozoal", aliases: ["Flagyl", "Emgyl", "Metro"], source: "Nigerian pharmacy listings" },
  { rxcui: "LOCAL-AMOXICILLIN-CLAVULANATE", genericName: "Amoxicillin + Clavulanic Acid", category: "Antibiotic combination", aliases: ["Augmentin", "Moxclav", "Clamoxin", "Clavam", "Klavox", "Myclav"], source: "Nigerian pharmacy listings" },
  { rxcui: "2194", genericName: "Cefuroxime", category: "Antibiotic", aliases: ["Zinnat", "Zinacef", "Cefurox", "Cefuzime"], source: "Nigerian pharmacy listings" },
  { rxcui: "4582", genericName: "Ferrous Sulfate", category: "Supplement", aliases: ["Feroglobin", "Feroglobin B12", "Fesulf"], source: "Nigerian supplement brand mapping" },
  { rxcui: "4614", genericName: "Folic Acid", category: "Supplement", aliases: ["Feroglobin", "Feroglobin B12", "Folate"], source: "Nigerian supplement brand mapping" },
  { rxcui: "9878", genericName: "Vitamin B12", category: "Supplement", aliases: ["Feroglobin", "Feroglobin B12", "Cyanocobalamin"], source: "Nigerian supplement brand mapping" },
  { rxcui: "LOCAL-RHZE", genericName: "Rifampicin + Isoniazid + Pyrazinamide + Ethambutol", category: "Tuberculosis combination", aliases: ["RHZE", "4FDC", "Akurit-4", "Forecox"], source: "Nigerian TB brand mapping" },
  { rxcui: "LOCAL-TENOFOVIR-LAMIVUDINE-DOLUTEGRAVIR", genericName: "Tenofovir + Lamivudine + Dolutegravir", category: "Antiretroviral combination", aliases: ["TLD", "Acriptega", "Telado"], source: "Nigerian HIV medicine mapping" },
  { rxcui: "LOCAL-BETAMETHASONE-CLOTRIMAZOLE-GENTAMICIN", genericName: "Betamethasone + Clotrimazole + Gentamicin", category: "Topical combination", aliases: ["Skineal", "Funbact-A", "Candiderm"], source: "Nigerian pharmacy listings" },
];
